### ISSUE TITLE
preprocessing of input data

### ISSUE THREAD

**Issue by ljc1993** [ZebinYang/gaminet#10]
Dear Gaminet Authors,
Thanks for producing such useful tool. You mentioned in your paper that the categorical variables are preprocessed using one-hot encoding, whereas in your 'bank marketing' example, you used label encoding. Is that an error or is there any reason you did so? Thanks.

Best

**Comment by ZebinYang** [comment]
Hi @ljc1993, we require categorical features to be preprocessed in the form of 0, 1, 2, ..., K-1 (K is the number of categories) beforing inputing to GAMI-Net. One-hot encoding is done in GAMI-Net internally.
