### ISSUE TITLE
error in interaction training stage

### ISSUE THREAD

**Issue by x1357** [ZebinYang/gaminet#11]
I installed gaminet v.0.5.9, and tried to run [GAMINet-demo.ipynb](https://github.com/ZebinYang/gaminet/blob/master/examples/GAMINet-demo.ipynb). but got the following error messages... it seems like the error maybe caused by Keras, rather than Gaminet. but I'm new to python, gaminet, tensorflow, so it would be appreciated if you could advice how I could fix the issue! - Many thanks!

##########Stage 2: interaction training start.##########
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [3], in <cell line: 9>()
      1 model = GAMINet(meta_info=meta_info, interact_num=20, 
      2                 interact_arch=[40] * 5, subnet_arch=[40] * 5, 
      3                 batch_size=200, task_type=task_type, activation_func=tf.nn.relu, 
   (...)
      7                 concave_list=None,
      8                 verbose=True, val_ratio=0.2, random_state=random_state)
----> 9 model.fit(train_x, train_y)
     11 val_x = train_x[model.val_idx, :]
     12 val_y = train_y[model.val_idx, :]

File C:\Python310\lib\site-packages\gaminet\gaminet.py:658, in GAMINet.fit(self, train_x, train_y, sample_weight)
    656 self.add_interaction(tr_x, tr_y, val_x, val_y, sample_weight)
    657 self.optimizer.lr.assign(self.lr_bp[1])
--> 658 self.fit_interaction(tr_x, tr_y, val_x, val_y, sample_weight)
    659 if self.verbose:
    660     print("#" * 10 + "Stage 2: interaction training stop." + "#" * 10)

File C:\Python310\lib\site-packages\gaminet\gaminet.py:504, in GAMINet.fit_interaction(self, tr_x, tr_y, val_x, val_y, sample_weight)
    502     batch_yy = tr_y[offset:(offset + self.batch_size)]
    503     batch_sw = tr_sw[offset:(offset + self.batch_size)]
--> 504     self.train_interaction(tf.cast(batch_xx, tf.float32), tf.cast(batch_yy, tf.float32), tf.cast(batch_sw, tf.float32))
    506 self.err_train_interaction_training.append(self.evaluate(tr_x, tr_y, tr_sw,
    507                                      main_effect_training=False, interaction_training=False))
    508 self.err_val_interaction_training.append(self.evaluate(val_x, val_y, sample_weight[self.val_idx],
    509                                      main_effect_training=False, interaction_training=False))

File C:\Python310\lib\site-packages\tensorflow\python\util\traceback_utils.py:153, in filter_traceback.<locals>.error_handler(*args, **kwargs)
    151 except Exception as e:
    152   filtered_tb = _process_traceback_frames(e.__traceback__)
--> 153   raise e.with_traceback(filtered_tb) from None
    154 finally:
    155   del filtered_tb

File ~\AppData\Local\Temp\__autograph_generated_file3d61t8bg.py:41, in outer_factory.<locals>.inner_factory.<locals>.tf__train_interaction(self, inputs, labels, sample_weight)
     39 ag__.for_stmt(ag__.converted_call(ag__.ld(range), (ag__.converted_call(ag__.ld(len), (ag__.ld(train_weights),), None, fscope),), None, fscope), None, loop_body, get_state_1, set_state_1, (), {'iterate_names': 'i'})
     40 grads = ag__.converted_call(ag__.ld(tape).gradient, (ag__.ld(total_loss), ag__.ld(train_weights_list)), None, fscope)
---> 41 ag__.converted_call(ag__.ld(self).optimizer.apply_gradients, (ag__.converted_call(ag__.ld(zip), (ag__.ld(grads), ag__.ld(train_weights_list)), None, fscope),), None, fscope)

File C:\Python310\lib\site-packages\keras\optimizers\optimizer_experimental\optimizer.py:1140, in Optimizer.apply_gradients(self, grads_and_vars, name, skip_gradients_aggregation, **kwargs)
   1138 if not skip_gradients_aggregation and experimental_aggregate_gradients:
   1139     grads_and_vars = self.aggregate_gradients(grads_and_vars)
-> 1140 return super().apply_gradients(grads_and_vars, name=name)

File C:\Python310\lib\site-packages\keras\optimizers\optimizer_experimental\optimizer.py:634, in _BaseOptimizer.apply_gradients(self, grads_and_vars, name)
    632 self._apply_weight_decay(trainable_variables)
    633 grads_and_vars = list(zip(grads, trainable_variables))
--> 634 iteration = self._internal_apply_gradients(grads_and_vars)
    636 # Apply variable constraints after applying gradients.
    637 for variable in trainable_variables:

File C:\Python310\lib\site-packages\keras\optimizers\optimizer_experimental\optimizer.py:1166, in Optimizer._internal_apply_gradients(self, grads_and_vars)
   1165 def _internal_apply_gradients(self, grads_and_vars):
-> 1166     return tf.__internal__.distribute.interim.maybe_merge_call(
   1167         self._distributed_apply_gradients_fn,
   1168         self._distribution_strategy,
   1169         grads_and_vars,
   1170     )

File C:\Python310\lib\site-packages\keras\optimizers\optimizer_experimental\optimizer.py:1216, in Optimizer._distributed_apply_gradients_fn(self, distribution, grads_and_vars, **kwargs)
   1213         return self._update_step(grad, var)
   1215 for grad, var in grads_and_vars:
-> 1216     distribution.extended.update(
   1217         var, apply_grad_to_update_var, args=(grad,), group=False
   1218     )
   1220 if self.use_ema:
   1221     _, var_list = zip(*grads_and_vars)

File C:\Python310\lib\site-packages\keras\optimizers\optimizer_experimental\optimizer.py:1213, in Optimizer._distributed_apply_gradients_fn.<locals>.apply_grad_to_update_var(var, grad)
   1211     return self._update_step_xla(grad, var, id(self._var_key(var)))
   1212 else:
-> 1213     return self._update_step(grad, var)

File C:\Python310\lib\site-packages\keras\optimizers\optimizer_experimental\optimizer.py:216, in _BaseOptimizer._update_step(self, gradient, variable)
    214     return
    215 if self._var_key(variable) not in self._index_dict:
--> 216     raise KeyError(
    217         f"The optimizer cannot recognize variable {variable.name}. "
    218         "This usually means you are trying to call the optimizer to "
    219         "update different parts of the model separately. Please call "
    220         "`optimizer.build(variables)` with the full list of trainable "
    221         "variables before the training loop or use legacy optimizer "
    222         "`tf.keras.optimizers.legacy.{self.__class__.__name__}."
    223     )
    224 self.update_step(gradient, variable)

KeyError: in user code:

    File "C:\Python310\lib\site-packages\gaminet\gaminet.py", line 250, in train_interaction  *
        self.optimizer.apply_gradients(zip(grads, train_weights_list))
    File "C:\Python310\lib\site-packages\keras\optimizers\optimizer_experimental\optimizer.py", line 1140, in apply_gradients  **
        return super().apply_gradients(grads_and_vars, name=name)
    File "C:\Python310\lib\site-packages\keras\optimizers\optimizer_experimental\optimizer.py", line 634, in apply_gradients
        iteration = self._internal_apply_gradients(grads_and_vars)
    File "C:\Python310\lib\site-packages\keras\optimizers\optimizer_experimental\optimizer.py", line 1166, in _internal_apply_gradients
        return tf.__internal__.distribute.interim.maybe_merge_call(
    File "C:\Python310\lib\site-packages\keras\optimizers\optimizer_experimental\optimizer.py", line 1216, in _distributed_apply_gradients_fn
        distribution.extended.update(
    File "C:\Python310\lib\site-packages\keras\optimizers\optimizer_experimental\optimizer.py", line 1213, in apply_grad_to_update_var  **
        return self._update_step(grad, var)
    File "C:\Python310\lib\site-packages\keras\optimizers\optimizer_experimental\optimizer.py", line 216, in _update_step
        raise KeyError(

    KeyError: 'The optimizer cannot recognize variable gami_net/interaction_block/interactnetwork/dense_600/kernel:0. This usually means you are trying to call the optimizer to update different parts of the model separately. Please call `optimizer.build(variables)` with the full list of trainable variables before the training loop or use legacy optimizer `tf.keras.optimizers.legacy.{self.__class__.__name__}.'

​

**Comment by kkkkkklong** [comment]
As a fresh graduate student in statistics, I have encountered the same problem. If Dr. Yang is free, please answer, I would be very grateful!

**Comment by ZebinYang** [comment]
Hi @kkkkkklong and @x1357, 

This error is due to the recent update of TensorFlow. You can avoid this by

1. Downgrade TensorFlow from 2.11 to 2.8.
2. Or change "tf.keras.optimizers.Adam()" to "tf.keras.optimizers.legacy.Adam()" in line 141 of C:\Python310\lib\site-packages\gaminet\gaminet.py

Alternatively, we may want to take a look at our PiML toolbox (https://github.com/SelfExplainML/PiML-Toolbox/), which integrates GAMI-Net and many other interpretable machine-learning models.

**Comment by kkkkkklong** [comment]
> Hi @kkkkkklong and @x1357,
> 
> This error is due to the recent update of TensorFlow. You can avoid this by
> 
> 1. Downgrade TensorFlow from 2.11 to 2.8.
> 2. Or change "tf.keras.optimizers.Adam()" to "tf.keras.optimizers.legacy.Adam()" in line 141 of C:\Python310\lib\site-packages\gaminet\gaminet.py
> 
> Alternatively, we may want to take a look at our PiML toolbox (https://github.com/SelfExplainML/PiML-Toolbox/), which integrates GAMI-Net and many other interpretable machine-learning models.

@ZebinYang Thanks for your relpy!

**Comment by x1357** [comment]
@ZebinYang Thanks a lot for your reply. I can confirm the demo works now! - Thank you!
