### ISSUE TITLE
GAMI-Net for Multiclass Problem

### ISSUE THREAD

**Issue by kkkkkklong** [ZebinYang/gaminet#12]
Excuse me, I have a question, can gaminet be used for multi-classification problems？In multi-classification problem, I changed BinaryCrossentropy loss to CategoricalCrossentropy loss, but the loss doesn't drop during training, do you know what's going on?Thank you for your prompt attention to this matter and I appreciate your early reply.

**Comment by ZebinYang** [comment]
Hi, the current codebase does not support multi-classification. 

You will need to modify the codes a little bit—for instance, the number of output layer units and the explanation functions.

**Comment by kkkkkklong** [comment]
> Hi, the current codebase does not support multi-classification.
> 
> You will need to modify the codes a little bit—for instance, the number of output layer units and the explanation functions.

Thank you very much for your reply, I will try to modify it. I really appreciate your contributions in PiML. If you encounter new problems in the future, I hope you will not hesitate to teach me.
