### ISSUE TITLE
About gaminet tuning problem

### ISSUE THREAD

**Issue by kkkkkklong** [ZebinYang/gaminet#13]
Sorry to bother you again,
- when I use gaminet for binary classification, I find that its pre, acc, F1-score, and recall are not as good as XGboost. I think it may be necessary to adjust the parameters of gaminet. What libraries can be used to adjust the parameters of gaminet? 
- Looking forward to your reply, I will be very grateful.

**Comment by ZebinYang** [comment]
Hi @kkkkkklong, 

You may want to do some hyperparameter optimization. Actually, many HPO frameworks are available, for example, I also have a Python package to do so (https://github.com/ZebinYang/SeqUD). You may also find many alternatives here https://zebinyang.github.io/SeqUD/build/html/resources.html

**Comment by kkkkkklong** [comment]
Special thanks to you, Dr. Yang. Your helping spirit will inspire me to continue my research
