### ISSUE TITLE
Notes, Examples, Documentation or Intuition around "arch"

### ISSUE THREAD

**Issue by JoshuaC3** [ZebinYang/gaminet#4]
What are `subnet_arch` and `interaction_arch`? Any docs, examples or hints on this?

Many thanks!!

**Comment by ZebinYang** [comment]
They are the hidden layer architectures of main effect subnetworks and pairwise interaction subnetworks, respectively.
For example, subnet_arch=[10, 6] refers to 2 hidden layers with 10 nodes in the first hidden layer and 6 nodes in the second hidden layer.

**Comment by JoshuaC3** [comment]
Thank you ZebinYang!
