### ISSUE TITLE
Adding code to simulation scenario to reproduce ground-truth figure 

### ISSUE THREAD

**Issue by aay993** [ZebinYang/gaminet#7]
Would you be able to provide code alongside the example simulation study to reproduce the ground-truth plot? I.e. Figure 4A from the GAMI-Net paper: https://arxiv.org/pdf/2003.07132.pdf?

**Comment by ZebinYang** [comment]
``
import os
import numpy as np
import pandas as pd
import matplotlib.lines as mlines
from matplotlib import pyplot as plt
import matplotlib.gridspec as gridspec
from sklearn.preprocessing import MinMaxScaler

def cliff(x):
    # x1: -20,20
    # x2: -10, 5
    x1, x2 = x
    x1 = (2 * x1 - 1) * 20
    x2 = (2 * x2 - 1) * 7.5 - 2.5
    term1 = -0.5 * x1 ** 2 / 100
    term2 = -0.5 * (x2 + 0.03 * x1 ** 2 - 3) ** 2
    y = 10 * np.exp(term1 + term2)
    return  y

def sin_curve(x):
    x1, x2 = x
    return 3 * np.sin(2 * np.pi * x1 * x2)

grid_size = 101
x_grid = np.linspace(0, 1, grid_size)
subfigs = {"X1":{"inputs":x_grid,
                 "outputs":8 * (x_grid - 0.5) ** 2 
                 - np.mean(8 * (x_grid - 0.5) ** 2)}, 
           "X2":{"inputs":x_grid,
                 "outputs":0.1 * np.exp(-8 * x_grid + 4)
                 - np.mean(0.1 * np.exp(-8 * x_grid + 4))}, 
           "X3":{"inputs":x_grid,
                 "outputs":sin_curve(np.meshgrid(x_grid, x_grid)).mean(0)
                 - sin_curve(np.meshgrid(x_grid, x_grid)).mean(0).mean()}, 
           "X4":{"inputs":x_grid,
                 "outputs":sin_curve(np.meshgrid(x_grid, x_grid)).mean(1) 
                 - sin_curve(np.meshgrid(x_grid, x_grid)).mean(1).mean()}, 
           "X5":{"inputs":x_grid,
                 "outputs":cliff(np.meshgrid(x_grid, x_grid)).mean(0) 
                 - cliff(np.meshgrid(x_grid, x_grid)).mean(0).mean()}, 
           "X6":{"inputs":x_grid,
                 "outputs":cliff(np.meshgrid(x_grid, x_grid)).mean(1)
                 - cliff(np.meshgrid(x_grid, x_grid)).mean(1).mean()}, 
           "X3 vs. X4":{"input1":x_grid,
                        "input2":x_grid,
                        "outputs":(sin_curve(np.meshgrid(x_grid, x_grid))
           - sin_curve(np.meshgrid(x_grid, x_grid)).mean(0)
           - sin_curve(np.meshgrid(x_grid, x_grid)).mean(1).reshape([-1, 1]) 
           + sin_curve(np.meshgrid(x_grid, x_grid)).mean())}, 
           "X5 vs. X6":{"input1":x_grid,
                        "input2":x_grid,
                        "outputs":(cliff(np.meshgrid(x_grid, x_grid))
           - cliff(np.meshgrid(x_grid, x_grid)).mean(0)
           - cliff(np.meshgrid(x_grid, x_grid)).mean(1).reshape([-1, 1]) 
           + cliff(np.meshgrid(x_grid, x_grid)).mean())}}

idx = 0
max_ids = 8
cols_per_row = 4
fig = plt.figure(figsize=(5.2 * cols_per_row, 
                 4 * int(np.ceil(max_ids / cols_per_row))))
outer = gridspec.GridSpec(int(np.ceil(max_ids/cols_per_row)), cols_per_row, wspace=0.25, hspace=0.35)

var_list = []
for key, item in subfigs.items(): 
    var_list.append(np.var(item["outputs"]))
importance_ratio = 100 * np.round(var_list/np.sum(var_list), 4)
sort_index = list(np.argsort(importance_ratio[:6])[::-1]) + list(6 + np.argsort(importance_ratio[6:])[::-1])

for ind in sort_index: 
    key = list(subfigs.keys())[ind]
    item = subfigs[key]
    if "vs." not in key:

        subnets_inputs = item["inputs"]
        subnets_outputs = item["outputs"]

        ax1 = plt.Subplot(fig, outer[idx]) 
        ax1.plot(subnets_inputs, subnets_outputs)
        ax1.set_title(key + " (%0.2f %%)" % importance_ratio[ind], fontsize=12)
        fig.add_subplot(ax1)

    else:

        subnets_input1 = item["input1"]
        subnets_input2 = item["input2"]
        subnets_outputs = item["outputs"]
        ax = plt.Subplot(fig, outer[idx]) 
        axis_extent = [-0.5, grid_size + 0.5, -0.5, grid_size + 0.5]
        cf = ax.imshow(subnets_outputs[::-1, :], interpolation='nearest', aspect='auto', extent=axis_extent)
        ax.set_xticks(np.linspace(10, 100, 6))
        ax.set_xticklabels(np.round(np.linspace(subnets_input1.min() + 0.1 * (subnets_input1.max() - subnets_input1.min()),
                                                subnets_input1.max(), 6), 2))

        ax.set_yticks(np.linspace(10, 100, 6))
        ax.set_yticklabels(np.round(np.linspace(subnets_input1.min() + 0.1 * (subnets_input1.max() - subnets_input1.min()),
                                                subnets_input1.max(), 6), 2))
        response_precision = max(int(- np.log10(np.max(subnets_outputs) - np.min(subnets_outputs))) + 2, 0)
        fig.colorbar(cf, ax=ax, format='%0.' + str(response_precision) + 'f')
        ax.set_title(key + " (%0.2f %%)" % importance_ratio[ind], fontsize=12)
        fig.add_subplot(ax)

    idx = idx + 1

fig.savefig("./S1_GT.png", bbox_inches='tight', dpi=100)
fig.savefig("./S1_GT.eps", bbox_inches='tight', dpi=100)

**Comment by ZebinYang** [comment]
`
%matplotlib inline

import os
import numpy as np
import pandas as pd
import matplotlib.lines as mlines
from matplotlib import pyplot as plt
import matplotlib.gridspec as gridspec
from sklearn.preprocessing import MinMaxScaler

def cliff(x):
    # x1: -20,20
    # x2: -10, 5
    x1, x2 = x
    x1 = (2 * x1 - 1) * 20
    x2 = (2 * x2 - 1) * 7.5 - 2.5
    term1 = -0.5 * x1 ** 2 / 100
    term2 = -0.5 * (x2 + 0.03 * x1 ** 2 - 3) ** 2
    y = 10 * np.exp(term1 + term2)
    return  y

def sin_curve(x):
    x1, x2 = x
    return 3 * np.sin(2 * np.pi * x1 * x2)

grid_size = 101
x_grid = np.linspace(0, 1, grid_size)
subfigs = {"X1":{"inputs":x_grid,
                 "outputs":8 * (x_grid - 0.5) ** 2 
                 - np.mean(8 * (x_grid - 0.5) ** 2)}, 
           "X2":{"inputs":x_grid,
                 "outputs":0.1 * np.exp(-8 * x_grid + 4)
                 - np.mean(0.1 * np.exp(-8 * x_grid + 4))}, 
           "X3":{"inputs":x_grid,
                 "outputs":sin_curve(np.meshgrid(x_grid, x_grid)).mean(0)
                 - sin_curve(np.meshgrid(x_grid, x_grid)).mean(0).mean()}, 
           "X4":{"inputs":x_grid,
                 "outputs":sin_curve(np.meshgrid(x_grid, x_grid)).mean(1) 
                 - sin_curve(np.meshgrid(x_grid, x_grid)).mean(1).mean()}, 
           "X5":{"inputs":x_grid,
                 "outputs":cliff(np.meshgrid(x_grid, x_grid)).mean(0) 
                 - cliff(np.meshgrid(x_grid, x_grid)).mean(0).mean()}, 
           "X6":{"inputs":x_grid,
                 "outputs":cliff(np.meshgrid(x_grid, x_grid)).mean(1)
                 - cliff(np.meshgrid(x_grid, x_grid)).mean(1).mean()}, 
           "X3 vs. X4":{"input1":x_grid,
                        "input2":x_grid,
                        "outputs":(sin_curve(np.meshgrid(x_grid, x_grid))
           - sin_curve(np.meshgrid(x_grid, x_grid)).mean(0)
           - sin_curve(np.meshgrid(x_grid, x_grid)).mean(1).reshape([-1, 1]) 
           + sin_curve(np.meshgrid(x_grid, x_grid)).mean())}, 
           "X5 vs. X6":{"input1":x_grid,
                        "input2":x_grid,
                        "outputs":(cliff(np.meshgrid(x_grid, x_grid))
           - cliff(np.meshgrid(x_grid, x_grid)).mean(0)
           - cliff(np.meshgrid(x_grid, x_grid)).mean(1).reshape([-1, 1]) 
           + cliff(np.meshgrid(x_grid, x_grid)).mean())}}

idx = 0
max_ids = 8
cols_per_row = 4
fig = plt.figure(figsize=(5.2 * cols_per_row, 
                 4 * int(np.ceil(max_ids / cols_per_row))))
outer = gridspec.GridSpec(int(np.ceil(max_ids/cols_per_row)), cols_per_row, wspace=0.25, hspace=0.35)

var_list = []
for key, item in subfigs.items(): 
    var_list.append(np.var(item["outputs"]))
importance_ratio = 100 * np.round(var_list/np.sum(var_list), 4)
sort_index = list(np.argsort(importance_ratio[:6])[::-1]) + list(6 + np.argsort(importance_ratio[6:])[::-1])

for ind in sort_index: 
    key = list(subfigs.keys())[ind]
    item = subfigs[key]
    if "vs." not in key:

        subnets_inputs = item["inputs"]
        subnets_outputs = item["outputs"]

        ax1 = plt.Subplot(fig, outer[idx]) 
        ax1.plot(subnets_inputs, subnets_outputs)
        ax1.set_title(key + " (%0.2f %%)" % importance_ratio[ind], fontsize=12)
        fig.add_subplot(ax1)

    else:

        subnets_input1 = item["input1"]
        subnets_input2 = item["input2"]
        subnets_outputs = item["outputs"]
        ax = plt.Subplot(fig, outer[idx]) 
        axis_extent = [-0.5, grid_size + 0.5, -0.5, grid_size + 0.5]
        cf = ax.imshow(subnets_outputs[::-1, :], interpolation='nearest', aspect='auto', extent=axis_extent)
        ax.set_xticks(np.linspace(10, 100, 6))
        ax.set_xticklabels(np.round(np.linspace(subnets_input1.min() + 0.1 * (subnets_input1.max() - subnets_input1.min()),
                                                subnets_input1.max(), 6), 2))

        ax.set_yticks(np.linspace(10, 100, 6))
        ax.set_yticklabels(np.round(np.linspace(subnets_input1.min() + 0.1 * (subnets_input1.max() - subnets_input1.min()),
                                                subnets_input1.max(), 6), 2))
        response_precision = max(int(- np.log10(np.max(subnets_outputs) - np.min(subnets_outputs))) + 2, 0)
        fig.colorbar(cf, ax=ax, format='%0.' + str(response_precision) + 'f')
        ax.set_title(key + " (%0.2f %%)" % importance_ratio[ind], fontsize=12)
        fig.add_subplot(ax)

    idx = idx + 1

fig.savefig("./S1_GT.png", bbox_inches='tight', dpi=100)
fig.savefig("./S1_GT.eps", bbox_inches='tight', dpi=100)
`

**Comment by ZebinYang** [comment]
%matplotlib inline

import os
import numpy as np
import pandas as pd
import matplotlib.lines as mlines
from matplotlib import pyplot as plt
import matplotlib.gridspec as gridspec
from sklearn.preprocessing import MinMaxScaler

def cliff(x):
# x1: -20,20
# x2: -10, 5
x1, x2 = x
x1 = (2 * x1 - 1) * 20
x2 = (2 * x2 - 1) * 7.5 - 2.5
term1 = -0.5 * x1 ** 2 / 100
term2 = -0.5 * (x2 + 0.03 * x1 ** 2 - 3) ** 2
y = 10 * np.exp(term1 + term2)
return y

def sin_curve(x):
x1, x2 = x
return 3 * np.sin(2 * np.pi * x1 * x2)

grid_size = 101
x_grid = np.linspace(0, 1, grid_size)
subfigs = {"X1":{"inputs":x_grid,
"outputs":8 * (x_grid - 0.5) ** 2
- np.mean(8 * (x_grid - 0.5) ** 2)},
"X2":{"inputs":x_grid,
"outputs":0.1 * np.exp(-8 * x_grid + 4)
- np.mean(0.1 * np.exp(-8 * x_grid + 4))},
"X3":{"inputs":x_grid,
"outputs":sin_curve(np.meshgrid(x_grid, x_grid)).mean(0)
- sin_curve(np.meshgrid(x_grid, x_grid)).mean(0).mean()},
"X4":{"inputs":x_grid,
"outputs":sin_curve(np.meshgrid(x_grid, x_grid)).mean(1)
- sin_curve(np.meshgrid(x_grid, x_grid)).mean(1).mean()},
"X5":{"inputs":x_grid,
"outputs":cliff(np.meshgrid(x_grid, x_grid)).mean(0)
- cliff(np.meshgrid(x_grid, x_grid)).mean(0).mean()},
"X6":{"inputs":x_grid,
"outputs":cliff(np.meshgrid(x_grid, x_grid)).mean(1)
- cliff(np.meshgrid(x_grid, x_grid)).mean(1).mean()},
"X3 vs. X4":{"input1":x_grid,
"input2":x_grid,
"outputs":(sin_curve(np.meshgrid(x_grid, x_grid))
- sin_curve(np.meshgrid(x_grid, x_grid)).mean(0)
- sin_curve(np.meshgrid(x_grid, x_grid)).mean(1).reshape([-1, 1])
+ sin_curve(np.meshgrid(x_grid, x_grid)).mean())},
"X5 vs. X6":{"input1":x_grid,
"input2":x_grid,
"outputs":(cliff(np.meshgrid(x_grid, x_grid))
- cliff(np.meshgrid(x_grid, x_grid)).mean(0)
- cliff(np.meshgrid(x_grid, x_grid)).mean(1).reshape([-1, 1])
+ cliff(np.meshgrid(x_grid, x_grid)).mean())}}

idx = 0
max_ids = 8
cols_per_row = 4
fig = plt.figure(figsize=(5.2 * cols_per_row,
4 * int(np.ceil(max_ids / cols_per_row))))
outer = gridspec.GridSpec(int(np.ceil(max_ids/cols_per_row)), cols_per_row, wspace=0.25, hspace=0.35)

var_list = []
for key, item in subfigs.items():
var_list.append(np.var(item["outputs"]))
importance_ratio = 100 * np.round(var_list/np.sum(var_list), 4)
sort_index = list(np.argsort(importance_ratio[:6])[::-1]) + list(6 + np.argsort(importance_ratio[6:])[::-1])

for ind in sort_index:
key = list(subfigs.keys())[ind]
item = subfigs[key]
if "vs." not in key:

    subnets_inputs = item["inputs"]
    subnets_outputs = item["outputs"]

    ax1 = plt.Subplot(fig, outer[idx]) 
    ax1.plot(subnets_inputs, subnets_outputs)
    ax1.set_title(key + " (%0.2f %%)" % importance_ratio[ind], fontsize=12)
    fig.add_subplot(ax1)

else:

    subnets_input1 = item["input1"]
    subnets_input2 = item["input2"]
    subnets_outputs = item["outputs"]
    ax = plt.Subplot(fig, outer[idx]) 
    axis_extent = [-0.5, grid_size + 0.5, -0.5, grid_size + 0.5]
    cf = ax.imshow(subnets_outputs[::-1, :], interpolation='nearest', aspect='auto', extent=axis_extent)
    ax.set_xticks(np.linspace(10, 100, 6))
    ax.set_xticklabels(np.round(np.linspace(subnets_input1.min() + 0.1 * (subnets_input1.max() - subnets_input1.min()),
                                            subnets_input1.max(), 6), 2))

    ax.set_yticks(np.linspace(10, 100, 6))
    ax.set_yticklabels(np.round(np.linspace(subnets_input1.min() + 0.1 * (subnets_input1.max() - subnets_input1.min()),
                                            subnets_input1.max(), 6), 2))
    response_precision = max(int(- np.log10(np.max(subnets_outputs) - np.min(subnets_outputs))) + 2, 0)
    fig.colorbar(cf, ax=ax, format='%0.' + str(response_precision) + 'f')
    ax.set_title(key + " (%0.2f %%)" % importance_ratio[ind], fontsize=12)
    fig.add_subplot(ax)

idx = idx + 1
fig.savefig("./S1_GT.png", bbox_inches='tight', dpi=100)
fig.savefig("./S1_GT.eps", bbox_inches='tight', dpi=100)

**Comment by ZebinYang** [comment]
"""
%matplotlib inline

import os
import numpy as np
import pandas as pd
import matplotlib.lines as mlines
from matplotlib import pyplot as plt
import matplotlib.gridspec as gridspec
from sklearn.preprocessing import MinMaxScaler

def cliff(x):
# x1: -20,20
# x2: -10, 5
x1, x2 = x
x1 = (2 * x1 - 1) * 20
x2 = (2 * x2 - 1) * 7.5 - 2.5
term1 = -0.5 * x1 ** 2 / 100
term2 = -0.5 * (x2 + 0.03 * x1 ** 2 - 3) ** 2
y = 10 * np.exp(term1 + term2)
return y

def sin_curve(x):
x1, x2 = x
return 3 * np.sin(2 * np.pi * x1 * x2)

grid_size = 101
x_grid = np.linspace(0, 1, grid_size)
subfigs = {"X1":{"inputs":x_grid,
"outputs":8 * (x_grid - 0.5) ** 2
- np.mean(8 * (x_grid - 0.5) ** 2)},
"X2":{"inputs":x_grid,
"outputs":0.1 * np.exp(-8 * x_grid + 4)
- np.mean(0.1 * np.exp(-8 * x_grid + 4))},
"X3":{"inputs":x_grid,
"outputs":sin_curve(np.meshgrid(x_grid, x_grid)).mean(0)
- sin_curve(np.meshgrid(x_grid, x_grid)).mean(0).mean()},
"X4":{"inputs":x_grid,
"outputs":sin_curve(np.meshgrid(x_grid, x_grid)).mean(1)
- sin_curve(np.meshgrid(x_grid, x_grid)).mean(1).mean()},
"X5":{"inputs":x_grid,
"outputs":cliff(np.meshgrid(x_grid, x_grid)).mean(0)
- cliff(np.meshgrid(x_grid, x_grid)).mean(0).mean()},
"X6":{"inputs":x_grid,
"outputs":cliff(np.meshgrid(x_grid, x_grid)).mean(1)
- cliff(np.meshgrid(x_grid, x_grid)).mean(1).mean()},
"X3 vs. X4":{"input1":x_grid,
"input2":x_grid,
"outputs":(sin_curve(np.meshgrid(x_grid, x_grid))
- sin_curve(np.meshgrid(x_grid, x_grid)).mean(0)
- sin_curve(np.meshgrid(x_grid, x_grid)).mean(1).reshape([-1, 1])
+ sin_curve(np.meshgrid(x_grid, x_grid)).mean())},
"X5 vs. X6":{"input1":x_grid,
"input2":x_grid,
"outputs":(cliff(np.meshgrid(x_grid, x_grid))
- cliff(np.meshgrid(x_grid, x_grid)).mean(0)
- cliff(np.meshgrid(x_grid, x_grid)).mean(1).reshape([-1, 1])
+ cliff(np.meshgrid(x_grid, x_grid)).mean())}}

idx = 0
max_ids = 8
cols_per_row = 4
fig = plt.figure(figsize=(5.2 * cols_per_row,
4 * int(np.ceil(max_ids / cols_per_row))))
outer = gridspec.GridSpec(int(np.ceil(max_ids/cols_per_row)), cols_per_row, wspace=0.25, hspace=0.35)

var_list = []
for key, item in subfigs.items():
var_list.append(np.var(item["outputs"]))
importance_ratio = 100 * np.round(var_list/np.sum(var_list), 4)
sort_index = list(np.argsort(importance_ratio[:6])[::-1]) + list(6 + np.argsort(importance_ratio[6:])[::-1])

for ind in sort_index:
key = list(subfigs.keys())[ind]
item = subfigs[key]
if "vs." not in key:

    subnets_inputs = item["inputs"]
    subnets_outputs = item["outputs"]

    ax1 = plt.Subplot(fig, outer[idx]) 
    ax1.plot(subnets_inputs, subnets_outputs)
    ax1.set_title(key + " (%0.2f %%)" % importance_ratio[ind], fontsize=12)
    fig.add_subplot(ax1)

else:

    subnets_input1 = item["input1"]
    subnets_input2 = item["input2"]
    subnets_outputs = item["outputs"]
    ax = plt.Subplot(fig, outer[idx]) 
    axis_extent = [-0.5, grid_size + 0.5, -0.5, grid_size + 0.5]
    cf = ax.imshow(subnets_outputs[::-1, :], interpolation='nearest', aspect='auto', extent=axis_extent)
    ax.set_xticks(np.linspace(10, 100, 6))
    ax.set_xticklabels(np.round(np.linspace(subnets_input1.min() + 0.1 * (subnets_input1.max() - subnets_input1.min()),
                                            subnets_input1.max(), 6), 2))

    ax.set_yticks(np.linspace(10, 100, 6))
    ax.set_yticklabels(np.round(np.linspace(subnets_input1.min() + 0.1 * (subnets_input1.max() - subnets_input1.min()),
                                            subnets_input1.max(), 6), 2))
    response_precision = max(int(- np.log10(np.max(subnets_outputs) - np.min(subnets_outputs))) + 2, 0)
    fig.colorbar(cf, ax=ax, format='%0.' + str(response_precision) + 'f')
    ax.set_title(key + " (%0.2f %%)" % importance_ratio[ind], fontsize=12)
    fig.add_subplot(ax)

idx = idx + 1
fig.savefig("./S1_GT.png", bbox_inches='tight', dpi=100)
fig.savefig("./S1_GT.eps", bbox_inches='tight', dpi=100)
"""

**Comment by ZebinYang** [comment]
```
import os
import numpy as np
import pandas as pd
import matplotlib.lines as mlines
from matplotlib import pyplot as plt
import matplotlib.gridspec as gridspec

def cliff(x):
    # x1: -20,20
    # x2: -10, 5
    x1, x2 = x
    x1 = (2 * x1 - 1) * 20
    x2 = (2 * x2 - 1) * 7.5 - 2.5
    term1 = -0.5 * x1 ** 2 / 100
    term2 = -0.5 * (x2 + 0.03 * x1 ** 2 - 3) ** 2
    y = 10 * np.exp(term1 + term2)
    return  y

def sin_curve(x):
    x1, x2 = x
    return 3 * np.sin(2 * np.pi * x1 * x2)

grid_size = 101
x_grid = np.linspace(0, 1, grid_size)
subfigs = {"X1":{"inputs":x_grid,
                 "outputs":8 * (x_grid - 0.5) ** 2 
                 - np.mean(8 * (x_grid - 0.5) ** 2)}, 
           "X2":{"inputs":x_grid,
                 "outputs":0.1 * np.exp(-8 * x_grid + 4)
                 - np.mean(0.1 * np.exp(-8 * x_grid + 4))}, 
           "X3":{"inputs":x_grid,
                 "outputs":sin_curve(np.meshgrid(x_grid, x_grid)).mean(0)
                 - sin_curve(np.meshgrid(x_grid, x_grid)).mean(0).mean()}, 
           "X4":{"inputs":x_grid,
                 "outputs":sin_curve(np.meshgrid(x_grid, x_grid)).mean(1) 
                 - sin_curve(np.meshgrid(x_grid, x_grid)).mean(1).mean()}, 
           "X5":{"inputs":x_grid,
                 "outputs":cliff(np.meshgrid(x_grid, x_grid)).mean(0) 
                 - cliff(np.meshgrid(x_grid, x_grid)).mean(0).mean()}, 
           "X6":{"inputs":x_grid,
                 "outputs":cliff(np.meshgrid(x_grid, x_grid)).mean(1)
                 - cliff(np.meshgrid(x_grid, x_grid)).mean(1).mean()}, 
           "X3 vs. X4":{"input1":x_grid,
                        "input2":x_grid,
                        "outputs":(sin_curve(np.meshgrid(x_grid, x_grid))
           - sin_curve(np.meshgrid(x_grid, x_grid)).mean(0)
           - sin_curve(np.meshgrid(x_grid, x_grid)).mean(1).reshape([-1, 1]) 
           + sin_curve(np.meshgrid(x_grid, x_grid)).mean())}, 
           "X5 vs. X6":{"input1":x_grid,
                        "input2":x_grid,
                        "outputs":(cliff(np.meshgrid(x_grid, x_grid))
           - cliff(np.meshgrid(x_grid, x_grid)).mean(0)
           - cliff(np.meshgrid(x_grid, x_grid)).mean(1).reshape([-1, 1]) 
           + cliff(np.meshgrid(x_grid, x_grid)).mean())}}

idx = 0
max_ids = 8
cols_per_row = 4
fig = plt.figure(figsize=(5.2 * cols_per_row, 
                 4 * int(np.ceil(max_ids / cols_per_row))))
outer = gridspec.GridSpec(int(np.ceil(max_ids/cols_per_row)), cols_per_row, wspace=0.25, hspace=0.35)

var_list = []
for key, item in subfigs.items(): 
    var_list.append(np.var(item["outputs"]))
importance_ratio = 100 * np.round(var_list/np.sum(var_list), 4)
sort_index = list(np.argsort(importance_ratio[:6])[::-1]) + list(6 + np.argsort(importance_ratio[6:])[::-1])

for ind in sort_index: 
    key = list(subfigs.keys())[ind]
    item = subfigs[key]
    if "vs." not in key:
        subnets_inputs = item["inputs"]
        subnets_outputs = item["outputs"]

        ax1 = plt.Subplot(fig, outer[idx]) 
        ax1.plot(subnets_inputs, subnets_outputs)
        ax1.set_title(key + " (%0.2f %%)" % importance_ratio[ind], fontsize=12)
        fig.add_subplot(ax1)

    else:

        subnets_input1 = item["input1"]
        subnets_input2 = item["input2"]
        subnets_outputs = item["outputs"]
        ax = plt.Subplot(fig, outer[idx]) 
        axis_extent = [-0.5, grid_size + 0.5, -0.5, grid_size + 0.5]
        cf = ax.imshow(subnets_outputs[::-1, :], interpolation='nearest', aspect='auto', extent=axis_extent)
        ax.set_xticks(np.linspace(10, 100, 6))
        ax.set_xticklabels(np.round(np.linspace(subnets_input1.min() + 0.1 * (subnets_input1.max() - subnets_input1.min()),
                                                subnets_input1.max(), 6), 2))

        ax.set_yticks(np.linspace(10, 100, 6))
        ax.set_yticklabels(np.round(np.linspace(subnets_input1.min() + 0.1 * (subnets_input1.max() - subnets_input1.min()),
                                                subnets_input1.max(), 6), 2))
        response_precision = max(int(- np.log10(np.max(subnets_outputs) - np.min(subnets_outputs))) + 2, 0)
        fig.colorbar(cf, ax=ax, format='%0.' + str(response_precision) + 'f')
        ax.set_title(key + " (%0.2f %%)" % importance_ratio[ind], fontsize=12)
        fig.add_subplot(ax)
    idx = idx + 1
fig.savefig("./S1_GT.png", bbox_inches='tight', dpi=100)
fig.savefig("./S1_GT.eps", bbox_inches='tight', dpi=100)
```

**Comment by ZebinYang** [comment]
```
import numpy as np
from matplotlib import pyplot as plt
import matplotlib.gridspec as gridspec

def cliff(x):
    # x1: -20,20
    # x2: -10, 5
    x1, x2 = x
    x1 = (2 * x1 - 1) * 20
    x2 = (2 * x2 - 1) * 7.5 - 2.5
    term1 = -0.5 * x1 ** 2 / 100
    term2 = -0.5 * (x2 + 0.03 * x1 ** 2 - 3) ** 2
    y = 10 * np.exp(term1 + term2)
    return  y

def sin_curve(x):
    x1, x2 = x
    return 3 * np.sin(2 * np.pi * x1 * x2)

grid_size = 101
x_grid = np.linspace(0, 1, grid_size)
subfigs = {"X1":{"inputs":x_grid,
                 "outputs":8 * (x_grid - 0.5) ** 2 
                 - np.mean(8 * (x_grid - 0.5) ** 2)}, 
           "X2":{"inputs":x_grid,
                 "outputs":0.1 * np.exp(-8 * x_grid + 4)
                 - np.mean(0.1 * np.exp(-8 * x_grid + 4))}, 
           "X3":{"inputs":x_grid,
                 "outputs":sin_curve(np.meshgrid(x_grid, x_grid)).mean(0)
                 - sin_curve(np.meshgrid(x_grid, x_grid)).mean(0).mean()}, 
           "X4":{"inputs":x_grid,
                 "outputs":sin_curve(np.meshgrid(x_grid, x_grid)).mean(1) 
                 - sin_curve(np.meshgrid(x_grid, x_grid)).mean(1).mean()}, 
           "X5":{"inputs":x_grid,
                 "outputs":cliff(np.meshgrid(x_grid, x_grid)).mean(0) 
                 - cliff(np.meshgrid(x_grid, x_grid)).mean(0).mean()}, 
           "X6":{"inputs":x_grid,
                 "outputs":cliff(np.meshgrid(x_grid, x_grid)).mean(1)
                 - cliff(np.meshgrid(x_grid, x_grid)).mean(1).mean()}, 
           "X3 vs. X4":{"input1":x_grid,
                        "input2":x_grid,
                        "outputs":(sin_curve(np.meshgrid(x_grid, x_grid))
           - sin_curve(np.meshgrid(x_grid, x_grid)).mean(0)
           - sin_curve(np.meshgrid(x_grid, x_grid)).mean(1).reshape([-1, 1]) 
           + sin_curve(np.meshgrid(x_grid, x_grid)).mean())}, 
           "X5 vs. X6":{"input1":x_grid,
                        "input2":x_grid,
                        "outputs":(cliff(np.meshgrid(x_grid, x_grid))
           - cliff(np.meshgrid(x_grid, x_grid)).mean(0)
           - cliff(np.meshgrid(x_grid, x_grid)).mean(1).reshape([-1, 1]) 
           + cliff(np.meshgrid(x_grid, x_grid)).mean())}}

idx = 0
max_ids = 8
cols_per_row = 4
fig = plt.figure(figsize=(5.2 * cols_per_row, 
                 4 * int(np.ceil(max_ids / cols_per_row))))
outer = gridspec.GridSpec(int(np.ceil(max_ids/cols_per_row)), cols_per_row, wspace=0.25, hspace=0.35)

var_list = []
for key, item in subfigs.items(): 
    var_list.append(np.var(item["outputs"]))
importance_ratio = 100 * np.round(var_list/np.sum(var_list), 4)
sort_index = list(np.argsort(importance_ratio[:6])[::-1]) + list(6 + np.argsort(importance_ratio[6:])[::-1])

for ind in sort_index: 
    key = list(subfigs.keys())[ind]
    item = subfigs[key]
    if "vs." not in key:
        subnets_inputs = item["inputs"]
        subnets_outputs = item["outputs"]

        ax1 = plt.Subplot(fig, outer[idx]) 
        ax1.plot(subnets_inputs, subnets_outputs)
        ax1.set_title(key + " (%0.2f %%)" % importance_ratio[ind], fontsize=12)
        fig.add_subplot(ax1)

    else:

        subnets_input1 = item["input1"]
        subnets_input2 = item["input2"]
        subnets_outputs = item["outputs"]
        ax = plt.Subplot(fig, outer[idx]) 
        axis_extent = [-0.5, grid_size + 0.5, -0.5, grid_size + 0.5]
        cf = ax.imshow(subnets_outputs[::-1, :], interpolation='nearest', aspect='auto', extent=axis_extent)
        ax.set_xticks(np.linspace(10, 100, 6))
        ax.set_xticklabels(np.round(np.linspace(subnets_input1.min() + 0.1 * (subnets_input1.max() - subnets_input1.min()),
                                                subnets_input1.max(), 6), 2))

        ax.set_yticks(np.linspace(10, 100, 6))
        ax.set_yticklabels(np.round(np.linspace(subnets_input1.min() + 0.1 * (subnets_input1.max() - subnets_input1.min()),
                                                subnets_input1.max(), 6), 2))
        response_precision = max(int(- np.log10(np.max(subnets_outputs) - np.min(subnets_outputs))) + 2, 0)
        fig.colorbar(cf, ax=ax, format='%0.' + str(response_precision) + 'f')
        ax.set_title(key + " (%0.2f %%)" % importance_ratio[ind], fontsize=12)
        fig.add_subplot(ax)
    idx = idx + 1
fig.savefig("./S1_GT.png", bbox_inches='tight', dpi=100)
fig.savefig("./S1_GT.eps", bbox_inches='tight', dpi=100)
```
