### ISSUE TITLE
About 'mono_increasing_list'

### ISSUE THREAD

**Issue by Gongyinying** [ZebinYang/gaminet#8]
HI,it's a great  project.
I tried to reproduce your code, but there was a AttributeError: 'InteractionBlock' object has no attribute 'mono_increasing_list' error.I set momo_ increasing_ List parameter in  GAMINet, but typeerror:__ init__()  got an unexpected keyword argument 'mono_ increasing_ List ' error.

**Comment by ZebinYang** [comment]
Hi, 

The monotonic constraint is still under testing, and we have not uploaded it to pipy.
You may use the monotonic constraints by reinstalling it from github.
```
pip uninstall gaminet -y
pip install git+https://github.com/Zebinyang/gaminet.git
```
