### ISSUE TITLE
Include Interactions List 'Dense' object has no attribute 'bias' in 'Dense' object has no attribute 'bias' line 371, in center_interactions

### ISSUE THREAD

**Issue by NicoHambauer** [ZebinYang/gaminet#9]
Dear Gaminet Authors,
I love your work and explore new functions every time! I just discovered the include_interactions_list parameter. I am using adult dataset to compare GAMI-Net to EBM. However, there seems to be an internal error when setting this list of tuples! It seems, that the model wants to determine the interaction.bias but fails here.

```python
model_to_run = GAMINet(meta_info=meta_info, interact_num=20,
                         include_interaction_list=[(6, 1)], # equals include_interaction_list == ('age', 'hours.per.week') in my preprocessed dataframe
                         interact_arch=[40] * 5, subnet_arch=[40] * 5,
                         batch_size=1024, task_type="Classification", activation_func=tf.nn.relu,
                         main_effect_epochs=20, interaction_epochs=20, tuning_epochs=10,
                         # todo: main_effect_epochs=5000, interaction_epochs=5000, tuning_epochs=500,
                         lr_bp=[0.0001, 0.0001, 0.0001], early_stop_thres=[50, 50, 50],
                         heredity=True, loss_threshold=0.01, reg_clarity=1, # clarity 1.0
                         mono_increasing_list=[], mono_decreasing_list=[],  # the indices list of features
                         verbose=True, val_ratio=0.2, random_state=random_state)
```

```bash
Interaction training epoch: 19, train loss: 0.35906, val loss: 0.36314
Interaction training epoch: 20, train loss: 0.35829, val loss: 0.36233
Traceback (most recent call last):
  File "C:/Users/nico/PycharmProjects/gams_bacs_report/train_and_plot.py", line 639, in <module>
    Gaminet(X, y, dataset_name)
  File "C:/Users/nico/PycharmProjects/gams_bacs_report/train_and_plot.py", line 554, in Gaminet
    model_to_run.fit(np.array(X), np.array(y).reshape(-1, 1))
  File "C:\Users\nico\AppData\Roaming\Python\Python38\site-packages\gaminet\gaminet.py", line 644, in fit
    self.fit_interaction(tr_x, tr_y, val_x, val_y, sample_weight)
  File "C:\Users\nico\AppData\Roaming\Python\Python38\site-packages\gaminet\gaminet.py", line 512, in fit_interaction
    self.center_interactions()
  File "C:\Users\nico\AppData\Roaming\Python\Python38\site-packages\gaminet\gaminet.py", line 371, in center_interactions
    interact_bias = interact.output_layer.bias - interact.moving_mean
AttributeError: 'Dense' object has no attribute 'bias'

Process finished with exit code 1
```

Is this problem related to heredity=True? I am not sure after searching in your paper and docs/examples here on github.

Best regards,
Nico Hambauer

**Comment by ZebinYang** [comment]
> Dear Gaminet Authors, I love your work and explore new functions every time! I just discovered the include_interactions_list parameter. I am using adult dataset to compare GAMI-Net to EBM. However, there seems to be an internal error when setting this list of tuples! It seems, that the model wants to determine the interaction.bias but fails here.
> 
> ```python
> model_to_run = GAMINet(meta_info=meta_info, interact_num=20,
>                          include_interaction_list=[(6, 1)], # equals include_interaction_list == ('age', 'hours.per.week') in my preprocessed dataframe
>                          interact_arch=[40] * 5, subnet_arch=[40] * 5,
>                          batch_size=1024, task_type="Classification", activation_func=tf.nn.relu,
>                          main_effect_epochs=20, interaction_epochs=20, tuning_epochs=10,
>                          # todo: main_effect_epochs=5000, interaction_epochs=5000, tuning_epochs=500,
>                          lr_bp=[0.0001, 0.0001, 0.0001], early_stop_thres=[50, 50, 50],
>                          heredity=True, loss_threshold=0.01, reg_clarity=1, # clarity 1.0
>                          mono_increasing_list=[], mono_decreasing_list=[],  # the indices list of features
>                          verbose=True, val_ratio=0.2, random_state=random_state)
> ```
> 
> ```shell
> Interaction training epoch: 19, train loss: 0.35906, val loss: 0.36314
> Interaction training epoch: 20, train loss: 0.35829, val loss: 0.36233
> Traceback (most recent call last):
>   File "C:/Users/nico/PycharmProjects/gams_bacs_report/train_and_plot.py", line 639, in <module>
>     Gaminet(X, y, dataset_name)
>   File "C:/Users/nico/PycharmProjects/gams_bacs_report/train_and_plot.py", line 554, in Gaminet
>     model_to_run.fit(np.array(X), np.array(y).reshape(-1, 1))
>   File "C:\Users\nico\AppData\Roaming\Python\Python38\site-packages\gaminet\gaminet.py", line 644, in fit
>     self.fit_interaction(tr_x, tr_y, val_x, val_y, sample_weight)
>   File "C:\Users\nico\AppData\Roaming\Python\Python38\site-packages\gaminet\gaminet.py", line 512, in fit_interaction
>     self.center_interactions()
>   File "C:\Users\nico\AppData\Roaming\Python\Python38\site-packages\gaminet\gaminet.py", line 371, in center_interactions
>     interact_bias = interact.output_layer.bias - interact.moving_mean
> AttributeError: 'Dense' object has no attribute 'bias'
> 
> Process finished with exit code 1
> ```
> 
> Is this problem related to heredity=True? I am not sure after searching in your paper and docs/examples here on github.
> 
> Best regards, Nico Hambauer

Hi, thanks for pointing out this issue. 
This is a bug related to include_interaction_list. 
Accordingly, the code in the add_interaction function is updated.
